apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
     name: db
     labels:
      app: db
    spec:
     containers:
       - name: postgres
         image: postgres:15-apline
         env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
         ports: 
          - containerPort: 5432
            name: postgres 